### ISSUE TITLE
Create a block specific build pattern so scss and css can be local to the block folder.

### ISSUE THREAD

**Issue by schlotterer** [WebDevStudios/wd_f#38]
Create a blocks specific build process that creates and registers the css in the block folder. This allows for more efficient rendering of the css and again contributes to block portability.
- we can use laravel mix to create a custom distributed build for each block automatically
- creating custom builds is already in use for the critical.css - we can leverage this
- add the new built styles to the block registration (block.json)

**Comment by khleomix** [comment]
This was done before but we have to remove that so that Tailwind will work with only just one config file. All custom block styles will be added under the `src/scss/blocks/custom` folder. We can probably add that as part of the WPClI command. I'm pulling in @guzmandrade-wds here to see if this is something that we can do.

**Comment by guzmandrade-wds** [comment]
@khleomix https://github.com/WebDevStudios/wd_f/pull/44 adds to the `WP-CLI` command some changes, so block style files `src/scss/blocks/custom/<block_name>.scss` and `src/scss/blocks/custom/<block_name>.editor.scss` are used in the build/watch processes. Since the styles are added as `file:*` in `block.json` we don't need to enqueue them as with `critical.css`.

**Comment by khleomix** [comment]
Thanks @guzmandrade-wds. Closing this out as done.
